### ISSUE TITLE
Cannot work callback url on Android

### ISSUE THREAD

**Issue by HTsuruo** [0maru/twitter_login#2]
I build `/example`, but don't come back to App after authentication in chrome custom tabs on Android. 
filled in my URL scheme in `AndroidManifest.xml`.
anything else needed??

```
<intent-filter>
　<action android:name="android.intent.action.VIEW" />
　<category android:name="android.intent.category.DEFAULT" />
　<category android:name="android.intent.category.BROWSABLE" />
　<!-- Accepts URIs that begin with "example://gizmos” -->
　<data android:scheme="abcdefg" android:host="" />
</intent-filter>
```

```
final twitterLogin = TwitterLogin(
　apiKey: 'xxxxxxxxxxx',
　apiSecretKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    redirectURI: 'abcdefg://',
);
```

on iOS, it's work well. 
Thank you.

**Comment by 0maru** [comment]
I was setting up both the scheme and host.
But I fixed it to work with the scheme only.
I'm sure it will work when you update the plugin.
Thanks for using it.

**Comment by tsuruobiz** [comment]
@0maru 

Thanks you for your quick response. 
At first glance, it looks good.
But, Still not working.
Probably, my emulator cannot listen to the stream data from webview.
https://github.com/0maru/twitter_login/blob/3e92a4df444931d3ce40fbd8756c0a8a79c623c6/lib/src/twitter_login.dart#L60

So, freeze this screen..🤔
![image](https://user-images.githubusercontent.com/59546923/87106106-9ee6d680-c297-11ea-8c83-67bef916d00c.png)

it's work well, right?

my env is.. ↓

```
Android Emulator 
Pixel 3 API R
Target Android 10.0+ Google Play
```

Thank you.

**Comment by HTsuruo** [comment]
Thanks you for your quick response. 
At first glance, it looks good.
But, Still not working.
Probably, my emulator cannot listen to the stream data from webview.
https://github.com/0maru/twitter_login/blob/3e92a4df444931d3ce40fbd8756c0a8a79c623c6/lib/src/twitter_login.dart#L60

So, freeze this screen..🤔
![image](https://user-images.githubusercontent.com/59546923/87106106-9ee6d680-c297-11ea-8c83-67bef916d00c.png)

it's work well, right?

my env is.. ↓

```
Android Emulator 
Pixel 3 API R
Target Android 10.0+ Google Play
```

Thank you.

**Comment by 0maru** [comment]
I think so too.
I tried that out But it worked fine.

This is the AVD configuration
<img src="https://user-images.githubusercontent.com/43493921/87228473-75839300-c3dc-11ea-8822-980009548793.png" width="300">

Could you try test your deep links
```
adb shell am start -W -a android.intent.action.VIEW -d abcdefg:// com.maru.twitter_login_example
```

**Comment by HTsuruo** [comment]
sorry, It's my fault..
Probably, the problem is platform channel.
it's work well when change to stable channel.
Thank you.
